export let mac_data = [
  //macbook air
  {
    id: 1,
    brand: 'apple',
    series: 'macbook air',
    type: 'M1',
    display: 13,
    model: 'MacBook Air M1 2020 (8GB RAM | 256GB SSD)',
    color: ['space gray', 'silver', 'gold'],
    oldPrice: [28990000],
    actualPrice: [18790000],
    img: [
      './img/mac/macbookair/macbookair_m1_spacegray.webp',
      './img/mac/macbookair/macbookair_m1_silver.webp',
      './img/mac/macbookair/macbookair_m1_gold.webp',
    ],
  },
  {
    id: 2,
    brand: 'apple',
    series: 'macbook air',
    type: 'M2',
    display: 13,
    model: 'MacBook Air M2 2022 (8GB RAM | 256GB SSD)',
    color: ['space gray', 'silver', 'starlight', 'midnight'],
    oldPrice: [32990000],
    actualPrice: [27090000],
    img: [
      './img/mac/macbookair/macbookair_m2_spacegray.png',
      './img/mac/macbookair/macbookair_m2_silver.png',
      './img/mac/macbookair/macbookair_m2_starlight.png',
      './img/mac/macbookair/macbookair_m2_midnight.png',
    ],
  },
  {
    id: 3,
    brand: 'apple',
    series: 'macbook air',
    type: 'M2',
    display: 13,
    model: 'MacBook Air M2 2022 (8GB RAM | 512GB SSD)',
    color: ['space gray', 'silver', 'starlight', 'midnight'],
    oldPrice: [39990000],
    actualPrice: [32990000],
    img: [
      './img/mac/macbookair/macbookair_m2_spacegray.png',
      './img/mac/macbookair/macbookair_m2_silver.png',
      './img/mac/macbookair/macbookair_m2_starlight.png',
      './img/mac/macbookair/macbookair_m2_midnight.png',
    ],
  },
  {
    id: 4,
    brand: 'apple',
    series: 'macbook air',
    type: 'M2',
    display: 13,
    model: 'MacBook Air M2 2022 (16GB RAM | 256GB SSD)',
    color: ['space gray', 'silver', 'starlight', 'midnight'],
    oldPrice: [39990000],
    actualPrice: [32990000],
    img: [
      './img/mac/macbookair/macbookair_m2_spacegray.png',
      './img/mac/macbookair/macbookair_m2_silver.png',
      './img/mac/macbookair/macbookair_m2_starlight.png',
      './img/mac/macbookair/macbookair_m2_midnight.png',
    ],
  },
  {
    id: 5,
    brand: 'apple',
    series: 'macbook air',
    type: 'M2',
    display: 13,
    model: 'MacBook Air M2 2022 (16GB RAM | 512GB SSD)',
    color: ['space gray', 'silver', 'starlight', 'midnight'],
    oldPrice: [44990000],
    actualPrice: [38990000],
    img: [
      './img/mac/macbookair/macbookair_m2_spacegray.png',
      './img/mac/macbookair/macbookair_m2_silver.png',
      './img/mac/macbookair/macbookair_m2_starlight.png',
      './img/mac/macbookair/macbookair_m2_midnight.png',
    ],
  },
  //macbook pro
  {
    id: 6,
    brand: 'apple',
    series: 'macbook pro',
    type: 'M1',
    display: 13,
    model: 'MacBook Pro M1 2020 (8 core GPU| 8GB RAM| 256GB SSD)',
    color: ['silver'],
    oldPrice: [34990000],
    actualPrice: [27950000],
  },
  {
    id: 7,
    brand: 'apple',
    series: 'macbook pro',
    type: 'M2',
    display: 13,
    model: 'MacBook Pro 13 inch M2 (10 core| 8GB RAM| 256GB SSD)',
    color: ['space gray', 'silver'],
    oldPrice: [35990000],
    actualPrice: [29990000],
  },
  {
    id: 8,
    brand: 'apple',
    series: 'macbook pro',
    type: 'M2 Pro',
    display: 14,
    model: 'MacBook Pro 14 inch M2 Pro (16 Core| 16GB| 512GB)',
    color: ['space gray', 'silver'],
    oldPrice: [55000000],
    actualPrice: [48750000],
  },
  {
    id: 9,
    brand: 'apple',
    series: 'macbook pro',
    type: 'M2 Pro',
    display: 16,
    model: 'MacBook Pro 16 inch M2 Pro (19 Core| 16GB| 512GB)',
    color: ['space gray', 'silver'],
    oldPrice: [68000000],
    actualPrice: [60750000],
  },
  {
    id: 10,
    brand: 'apple',
    series: 'macbook pro',
    type: 'M2 Pro',
    display: 16,
    model: 'MacBook Pro 16 inch M2 Pro (19 Core| 16GB| 1TB)',
    color: ['space gray', 'silver'],
    oldPrice: [73000000],
    actualPrice: [65350000],
  },
  {
    id: 11,
    brand: 'apple',
    series: 'macbook pro',
    type: 'M2 Max',
    display: 16,
    model: 'MacBook Pro 16 inch M2 Max (38 Core| 32GB| 1TB)',
    color: ['space gray', 'silver'],
    oldPrice: [94990000],
    actualPrice: [83500000],
  },
];
