export const data_iphone = [
    {
        id: 1,
        brand: 'apple',
        series: 'se',
        model: 'iphone se 2022 64gb',
        memory: 64,
        color: ['midnight', 'starlight', '(product) red'],
        imgProduct: [
            '/img/iphone/iphoneSE/iphone_se_2022_midnight.webp',
            '/img/iphone/iphoneSE/iphone_se_2022_starlight.png',
            '/img/iphone/iphoneSE/iphone_se_2022_product_red.webp',
        ],
        oldPrice: 12990000,
        actualPrice: 9900000,
    },
    {
        id: 2,
        brand: 'apple',
        series: 'se',
        model: 'iphone se 2022 128gb',
        memory: 128,
        color: ['midnight', 'starlight', '(product) red'],
        imgProduct: [
            '/img/iphone/iphoneSE/iphone_se_2022_midnight.webp',
            '/img/iphone/iphoneSE/iphone_se_2022_starlight.png',
            '/img/iphone/iphoneSE/iphone_se_2022_product_red.webp',
        ],
        oldPrice: 13990000,
        actualPrice: 11990000,
    },
    {
        id: 3,
        brand: 'apple',
        series: 'se',
        model: 'iphone se 2022 256gb',
        memory: 256,
        color: ['midnight', 'starlight', '(product) red'],
        imgProduct: [
            '/img/iphone/iphoneSE/iphone_se_2022_midnight.webp',
            '/img/iphone/iphoneSE/iphone_se_2022_starlight.png',
            '/img/iphone/iphoneSE/iphone_se_2022_product_red.webp',
        ],
        oldPrice: 16990000,
        actualPrice: 14990000,
    },
    {
        id: 4,
        brand: 'apple',
        series: '11',
        model: 'iphone 11 64gb',
        memory: 64,
        color: ['black', 'white'],
        imgProduct: [
            '/img/iphone/iphone11/iphone_11_black.png',
            '/img/iphone/iphone11/iphone_11_white.png',
        ],
        oldPrice: 14990000,
        actualPrice: 10790000,
    },
    {
        id: 5,
        brand: 'apple',
        series: '11',
        model: 'iphone 11 128gb',
        memory: 128,
        color: ['black', 'white'],
        imgProduct: [
            '/img/iphone/iphone11/iphone_11_black.png',
            '/img/iphone/iphone11/iphone_11_white.png',
        ],
        oldPrice: 16990000,
        actualPrice: 12390000,
    },
    {
        id: 6,
        brand: 'apple',
        series: '12',
        model: 'iphone 12 64gb',
        memory: 64,
        color: ['black', 'white', '(product) red', 'blue', 'green', 'purple'],
        imgProduct: [
            '/img/iphone/iphone12/iphone_12_black.png',
            '/img/iphone/iphone12/iphone_12_white.png',
            '/img/iphone/iphone12/iphone_12_product_red.png',
            '/img/iphone/iphone12/iphone_12_blue.png',
            '/img/iphone/iphone12/iphone_12_green.png',
            '/img/iphone/iphone12/iphone_12_purple.png',
        ],
        oldPrice: 22990000,
        actualPrice: 14790000, 
    },
    {
        id: 7,
        brand: 'apple',
        series: '12',
        model: 'iphone 12 128gb',
        memory: 128,
        color: ['black', 'white', '(product) red', 'blue', 'green', 'purple'],
        imgProduct: [
            '/img/iphone/iphone12/iphone_12_black.png',
            '/img/iphone/iphone12/iphone_12_white.png',
            '/img/iphone/iphone12/iphone_12_product_red.png',
            '/img/iphone/iphone12/iphone_12_blue.png',
            '/img/iphone/iphone12/iphone_12_green.png',
            '/img/iphone/iphone12/iphone_12_purple.png',
        ],
        oldPrice: 24990000,
        actualPrice: 17790000,
    },
    {
        id: 8,
        brand: 'apple',
        series: '13',
        model: 'iphone 13 128gb',
        memory: 128,
        color: ['midnight', 'starlight', '(product) red', 'pink', 'blue', 'alpine green'],
        imgProduct: [
            '/img/iphone/iphone13/iphone_13_midnight.png',
            '/img/iphone/iphone13/iphone_13_starlight.png',
            '/img/iphone/iphone13/iphone_13_product_red.png',
            '/img/iphone/iphone13/iphone_13_pink.png',
            '/img/iphone/iphone13/iphone_13_blue.png',
            '/img/iphone/iphone13/iphone_13_alpine_green.png',
        ],
        oldPrice: 24990000, 
        actualPrice: 17490000, 
    },
    {
        id: 9,
        brand: 'apple',
        series: '13',
        model: 'iphone 13 256gb',
        memory: 256,
        color: ['midnight', 'starlight', '(product) red', 'pink', 'blue', 'alpine green'],
        imgProduct: [
            '/img/iphone/iphone13/iphone_13_midnight.png',
            '/img/iphone/iphone13/iphone_13_starlight.png',
            '/img/iphone/iphone13/iphone_13_product_red.png',
            '/img/iphone/iphone13/iphone_13_pink.png',
            '/img/iphone/iphone13/iphone_13_blue.png',
            '/img/iphone/iphone13/iphone_13_alpine_green.png',
        ],
        oldPrice:  26990000,
        actualPrice: 20950000,
    },
    {
        id: 10,
        brand: 'apple',
        series: '13',
        model: 'iphone 13 512gb',
        memory: 512,
        color: ['midnight', 'starlight', '(product) red', 'pink', 'blue', 'alpine green'],
        imgProduct: [
            '/img/iphone/iphone13/iphone_13_midnight.png',
            '/img/iphone/iphone13/iphone_13_starlight.png',
            '/img/iphone/iphone13/iphone_13_product_red.png',
            '/img/iphone/iphone13/iphone_13_pink.png',
            '/img/iphone/iphone13/iphone_13_blue.png',
            '/img/iphone/iphone13/iphone_13_alpine_green.png',
        ],
        oldPrice: 27990000,
        actualPrice: 21950000,
    },
    {
        id: 11,
        brand: 'apple',
        series: '13',
        model: 'iphone 13 mini 128gb',
        memory: 128, 
        color: ['midnight', 'starlight', '(product) red', 'pink', 'blue', 'alpine green'],
        imgProduct: [
            '/img/iphone/iphone13mini/iphone_13_mn_midnight.png',
            '/img/iphone/iphone13mini/iphone_13_mn_starlight.png',
            '/img/iphone/iphone13mini/iphone_13_mn_product_red.png',
            '/img/iphone/iphone13mini/iphone_13_mn_pink.png',
            '/img/iphone/iphone13mini/iphone_13_mn_blue.png',
            '/img/iphone/iphone13mini/iphone_13_mn_alpine_green.png',
        ],
        oldPrice: 21990000, 
        actualPrice: 16990000, 
    },
    {
        id: 12,
        brand: 'apple',
        series: '13',
        model: 'iphone 13 mini 256gb',
        memory: 256, 
        color: ['midnight', 'starlight', '(product) red', 'pink', 'blue', 'alpine green'],
        imgProduct: [
            '/img/iphone/iphone13mini/iphone_13_mn_midnight.png',
            '/img/iphone/iphone13mini/iphone_13_mn_starlight.png',
            '/img/iphone/iphone13mini/iphone_13_mn_product_red.png',
            '/img/iphone/iphone13mini/iphone_13_mn_pink.png',
            '/img/iphone/iphone13mini/iphone_13_mn_blue.png',
            '/img/iphone/iphone13mini/iphone_13_mn_alpine_green.png',
        ],
        oldPrice: 24990000, 
        actualPrice: 19990000, 
    },
    {
        id: 13,
        brand: 'apple',
        series: '13',
        model: 'iphone 13 mini 512gb',
        memory: 512,
        color: ['midnight', 'starlight', '(product) red', 'pink', 'blue', 'alpine green'],
        imgProduct: [
            '/img/iphone/iphone13mini/iphone_13_mn_midnight.png',
            '/img/iphone/iphone13mini/iphone_13_mn_starlight.png',
            '/img/iphone/iphone13mini/iphone_13_mn_product_red.png',
            '/img/iphone/iphone13mini/iphone_13_mn_pink.png',
            '/img/iphone/iphone13mini/iphone_13_mn_blue.png',
            '/img/iphone/iphone13mini/iphone_13_mn_alpine_green.png',
        ],
        oldPrice: 30990000,
        actualPrice: 23990000,
    },
    {
        id: 14,
        brand: 'apple',
        series: '14',
        model: 'iphone 14 128gb',
        memory: 128, 
        color: ['midnight', 'starlight', '(product) red', 'purple', 'blue'],
        imgProduct: [
            '/img/iphone/iphone14/iphone_14_midnight.png',
            '/img/iphone/iphone14/iphone_14_starlight.png',
            '/img/iphone/iphone14/iphone_14_product_red.png',
            '/img/iphone/iphone14/iphone_14_purple.png',
            '/img/iphone/iphone14/iphone_14_blue.png',
        ],
        oldPrice: 24990000, 
        actualPrice: 19790000, 
    },
    {
        id: 15,
        brand: 'apple',
        series: '14',
        model: 'iphone 14 256gb',
        memory: 256, 
        color: ['midnight', 'starlight', '(product) red', 'purple', 'blue'],
        imgProduct: [
            '/img/iphone/iphone14/iphone_14_midnight.png',
            '/img/iphone/iphone14/iphone_14_starlight.png',
            '/img/iphone/iphone14/iphone_14_product_red.png',
            '/img/iphone/iphone14/iphone_14_purple.png',
            '/img/iphone/iphone14/iphone_14_blue.png',
        ],
        oldPrice: 27990000, 
        actualPrice: 22490000, 
    },
    {
        id: 16,
        brand: 'apple',
        series: '14',
        model: 'iphone 14 512gb',
        memory: 512,
        color: ['midnight', 'starlight', '(product) red', 'purple', 'blue'],
        imgProduct: [
            '/img/iphone/iphone14/iphone_14_midnight.png',
            '/img/iphone/iphone14/iphone_14_starlight.png',
            '/img/iphone/iphone14/iphone_14_product_red.png',
            '/img/iphone/iphone14/iphone_14_purple.png',
            '/img/iphone/iphone14/iphone_14_blue.png',
        ],
        oldPrice: 33990000,
        actualPrice: 25690000,
    },
    {
        id: 17,
        brand: 'apple',
        series: '14',
        model: 'iphone 14 plus 128gb',
        memory: 128, 
        color: ['midnight', 'starlight', '(product) red', 'purple', 'blue'],
        imgProduct: [
            '/img/iphone/iphone14plus/iphone_14_plus_midnight.png',
            '/img/iphone/iphone14plus/iphone_14_plus_starlight.png',
            '/img/iphone/iphone14plus/iphone_14_plus_product_red.png',
            '/img/iphone/iphone14plus/iphone_14_plus_purple.png',
            '/img/iphone/iphone14plus/iphone_14_plus_blue.png',
        ],
        oldPrice: 27990000, 
        actualPrice: 22490000,
    },
    {
        id: 18,
        brand: 'apple',
        series: '14',
        model: 'iphone 14 plus 256gb',
        memory: 256, 
        color: ['midnight', 'starlight', '(product) red', 'purple', 'blue'],
        imgProduct: [
            '/img/iphone/iphone14plus/iphone_14_plus_midnight.png',
            '/img/iphone/iphone14plus/iphone_14_plus_starlight.png',
            '/img/iphone/iphone14plus/iphone_14_plus_product_red.png',
            '/img/iphone/iphone14plus/iphone_14_plus_purple.png',
            '/img/iphone/iphone14plus/iphone_14_plus_blue.png',
        ],
        oldPrice: 33990000, 
        actualPrice: 24790000, 
    },
    {
        id: 19,
        brand: 'apple',
        series: '14',
        model: 'iphone 14 plus 512gb',
        memory: 512,
        color: ['midnight', 'starlight', '(product) red', 'purple', 'blue'],
        imgProduct: [
            '/img/iphone/iphone14plus/iphone_14_plus_midnight.png',
            '/img/iphone/iphone14plus/iphone_14_plus_starlight.png',
            '/img/iphone/iphone14plus/iphone_14_plus_product_red.png',
            '/img/iphone/iphone14plus/iphone_14_plus_purple.png',
            '/img/iphone/iphone14plus/iphone_14_plus_blue.png',
        ],
        oldPrice: 36990000,
        actualPrice: 27390000,
    },
    {
        id: 20,
        brand: 'apple',
        series: '14',
        model: 'iphone 14 pro 128gb',
        memory: 128, 
        color: ['space black', 'silver', 'gold', 'deep purple'],
        imgProduct: [
            '/img/iphone/iphone14pro/iphone_14_pro_spaceblack.png',
            '/img/iphone/iphone14pro/iphone_14_pro_silver.png',
            '/img/iphone/iphone14pro/iphone_14_pro_gold.png',
            '/img/iphone/iphone14pro/iphone_14_pro_deeppurple.png',
        ],
        oldPrice: 30990000, 
        actualPrice: 25390000, 
    },
    {
        id: 21,
        brand: 'apple',
        series: '14',
        model: 'iphone 14 pro 256gb',
        memory: 256, 
        color: ['space black', 'silver', 'gold', 'deep purple'],
        imgProduct: [
            '/img/iphone/iphone14pro/iphone_14_pro_spaceblack.png',
            '/img/iphone/iphone14pro/iphone_14_pro_silver.png',
            '/img/iphone/iphone14pro/iphone_14_pro_gold.png',
            '/img/iphone/iphone14pro/iphone_14_pro_deeppurple.png',
        ],
        oldPrice: 34990000, 
        actualPrice: 27990000, 
    },
    {
        id: 22,
        brand: 'apple',
        series: '14',
        model: 'iphone 14 pro 512gb',
        memory: 512, 
        color: ['space black', 'silver', 'gold', 'deep purple'],
        imgProduct: [
            '/img/iphone/iphone14pro/iphone_14_pro_spaceblack.png',
            '/img/iphone/iphone14pro/iphone_14_pro_silver.png',
            '/img/iphone/iphone14pro/iphone_14_pro_gold.png',
            '/img/iphone/iphone14pro/iphone_14_pro_deeppurple.png',
        ],
        oldPrice: 40990000, 
        actualPrice: 32490000, 
    },
    {
        id: 23,
        brand: 'apple',
        series: '14',
        model: 'iphone 14 pro 1tb',
        memory: 1,
        color: ['space black', 'silver', 'gold', 'deep purple'],
        imgProduct: [
            '/img/iphone/iphone14pro/iphone_14_pro_spaceblack.png',
            '/img/iphone/iphone14pro/iphone_14_pro_silver.png',
            '/img/iphone/iphone14pro/iphone_14_pro_gold.png',
            '/img/iphone/iphone14pro/iphone_14_pro_deeppurple.png',
        ],
        oldPrice: 46990000,
        actualPrice: 37490000,
    },
    {
        id: 24,
        brand: 'apple',
        series: '14',
        model: 'iphone 14 pro max 128gb',
        memory: 128, 
        color: ['space black', 'silver', 'gold', 'deep purple'],
        imgProduct: [
            '/img/iphone/iphone14promax/iphone_14_pro_max_spaceblack.png',
            '/img/iphone/iphone14promax/iphone_14_pro_max_silver.png',
            '/img/iphone/iphone14promax/iphone_14_pro_max_gold.png',
            '/img/iphone/iphone14promax/iphone_14_pro_max_deeppurple.png',
        ],
        oldPrice: 34990000, 
        actualPrice: 27390000, 
    },
    {
        id: 25,
        brand: 'apple',
        series: '14',
        model: 'iphone 14 pro max 256gb',
        memory: 256, 
        color: ['space black', 'silver', 'gold', 'deep purple'],
        imgProduct: [
            '/img/iphone/iphone14promax/iphone_14_pro_max_spaceblack.png',
            '/img/iphone/iphone14promax/iphone_14_pro_max_silver.png',
            '/img/iphone/iphone14promax/iphone_14_pro_max_gold.png',
            '/img/iphone/iphone14promax/iphone_14_pro_max_deeppurple.png',
        ],
        oldPrice: 37490000, 
        actualPrice: 30190000, 
    },
    {
        id: 26,
        brand: 'apple',
        series: '14',
        model: 'iphone 14 pro max 512gb',
        memory: 512, 
        color: ['space black', 'silver', 'gold', 'deep purple'],
        imgProduct: [
            '/img/iphone/iphone14promax/iphone_14_pro_max_spaceblack.png',
            '/img/iphone/iphone14promax/iphone_14_pro_max_silver.png',
            '/img/iphone/iphone14promax/iphone_14_pro_max_gold.png',
            '/img/iphone/iphone14promax/iphone_14_pro_max_deeppurple.png',
        ],
        oldPrice: 43990000, 
        actualPrice: 37490000, 
    },
    {
        id: 27,
        brand: 'apple',
        series: '14',
        model: 'iphone 14 pro max 1tb',
        memory: 1,
        color: ['space black', 'silver', 'gold', 'deep purple'],
        imgProduct: [
            '/img/iphone/iphone14promax/iphone_14_pro_max_spaceblack.png',
            '/img/iphone/iphone14promax/iphone_14_pro_max_silver.png',
            '/img/iphone/iphone14promax/iphone_14_pro_max_gold.png',
            '/img/iphone/iphone14promax/iphone_14_pro_max_deeppurple.png',
        ],
        oldPrice: 49990000,
        actualPrice: 41990000,
    },
];