export let mac_data = [
  //macbook air
  {
    id: 1,
    brand: 'apple',
    series: 'macbook air',
    type: 'M1',
    display: 13,
    model: 'MacBook Air M1 2020 (8GB RAM | 256GB SSD)',
    color: ['space gray', 'silver', 'gold'],
    oldPrice: [28990000],
    actualPrice: [18790000],
    img: [
      './img/mac/macbookair/macbookair_m1_spacegray.webp',
      './img/mac/macbookair/macbookair_m1_silver.webp',
      './img/mac/macbookair/macbookair_m1_gold.webp',
    ],
  },
  {
    id: 2,
    brand: 'apple',
    series: 'macbook air',
    type: 'M2',
    display: 13,
    model: 'MacBook Air M2 2022 (8GB RAM | 256GB SSD)',
    color: ['space gray', 'silver', 'starlight', 'midnight'],
    oldPrice: [32990000],
    actualPrice: [27090000],
    img: [
      './img/mac/macbookair/macbookair_m2_spacegray.png',
      './img/mac/macbookair/macbookair_m2_silver.png',
      './img/mac/macbookair/macbookair_m2_starlight.png',
      './img/mac/macbookair/macbookair_m2_midnight.png',
    ],
  },
  {
    id: 3,
    brand: 'apple',
    series: 'macbook air',
    type: 'M2',
    display: 13,
    model: 'MacBook Air M2 2022 (8GB RAM | 512GB SSD)',
    color: ['space gray', 'silver', 'starlight', 'midnight'],
    oldPrice: [39990000],
    actualPrice: [32990000],
    img: [
      './img/mac/macbookair/macbookair_m2_spacegray.png',
      './img/mac/macbookair/macbookair_m2_silver.png',
      './img/mac/macbookair/macbookair_m2_starlight.png',
      './img/mac/macbookair/macbookair_m2_midnight.png',
    ],
  },
  {
    id: 4,
    brand: 'apple',
    series: 'macbook air',
    type: 'M2',
    display: 13,
    model: 'MacBook Air M2 2022 (16GB RAM | 256GB SSD)',
    color: ['space gray', 'silver', 'starlight', 'midnight'],
    oldPrice: [39990000],
    actualPrice: [32990000],
    img: [
      './img/mac/macbookair/macbookair_m2_spacegray.png',
      './img/mac/macbookair/macbookair_m2_silver.png',
      './img/mac/macbookair/macbookair_m2_starlight.png',
      './img/mac/macbookair/macbookair_m2_midnight.png',
    ],
  },
  {
    id: 5,
    brand: 'apple',
    series: 'macbook air',
    type: 'M2',
    display: 13,
    model: 'MacBook Air M2 2022 (16GB RAM | 512GB SSD)',
    color: ['space gray', 'silver', 'starlight', 'midnight'],
    oldPrice: [44990000],
    actualPrice: [38990000],
    img: [
      './img/mac/macbookair/macbookair_m2_spacegray.png',
      './img/mac/macbookair/macbookair_m2_silver.png',
      './img/mac/macbookair/macbookair_m2_starlight.png',
      './img/mac/macbookair/macbookair_m2_midnight.png',
    ],
  },
  //macbook pro
  {
    id: 6,
    brand: 'apple',
    series: 'macbook pro',
    type: 'M1',
    display: 13,
    model: 'MacBook Pro M1 2020 (8 core GPU| 8GB RAM| 256GB SSD)',
    color: ['silver'],
    oldPrice: [34990000],
    actualPrice: [27950000],
    img: ['./img/mac/macbookpro/macbookpro_m1_silver.webp'],
  },
  {
    id: 7,
    brand: 'apple',
    series: 'macbook pro',
    type: 'M1 Pro',
    display: 14,
    model: 'MacBook Pro 14 M1 Pro (16 Core/16GB/1TB)',
    color: ['space gray', 'silver'],
    oldPrice: [68000000],
    actualPrice: [49790000],
    img: [
      './img/mac/macbookpro/macbookpro_m1pro_spacegray.webp',
      './img/mac/macbookpro/macbookpro_m1pro_silver.webp',
    ],
  },
  {
    id: 8,
    brand: 'apple',
    series: 'macbook pro',
    type: 'M1 Max',
    display: 14,
    model: 'MacBook Pro 14 M1 Max (32 Core GPU| 1TB SSD)',
    color: ['silver'],
    oldPrice: [90500000],
    actualPrice: [78990000],
    img: ['./img/mac/macbookpro/macbookpro_m1max_silver.webp'],
  },
  {
    id: 9,
    brand: 'apple',
    series: 'macbook pro',
    type: 'M2',
    display: 13,
    model: 'MacBook Pro 13 inch M2 (10 core| 8GB RAM| 256GB SSD)',
    color: ['space gray', 'silver'],
    oldPrice: [35990000],
    actualPrice: [29990000],
    img: [
      './img/mac/macbookpro/macbookpro_m2_spacegray.webp',
      './img/mac/macbookpro/macbookpro_m2_silver.webp',
    ],
  },
  {
    id: 10,
    brand: 'apple',
    series: 'macbook pro',
    type: 'M2',
    display: 13,
    model: 'MacBook Pro 13 inch M2 (10 core| 8GB RAM| 512GB SSD)',
    color: ['space gray', 'silver'],
    oldPrice: [41990000],
    actualPrice: [34490000],
    img: [
      './img/mac/macbookpro/macbookpro_m2_spacegray.webp',
      './img/mac/macbookpro/macbookpro_m2_silver.webp',
    ],
  },
  {
    id: 11,
    brand: 'apple',
    series: 'macbook pro',
    type: 'M2',
    display: 13,
    model: 'MacBook Pro 13 inch M2 (10 core| 16GB RAM| 256GB SSD)',
    color: ['space gray', 'silver'],
    oldPrice: [41990000],
    actualPrice: [35990000],
    img: [
      './img/mac/macbookpro/macbookpro_m2_spacegray.webp',
      './img/mac/macbookpro/macbookpro_m2_silver.webp',
    ],
  },

  {
    id: 12,
    brand: 'apple',
    series: 'macbook pro',
    type: 'M2 Pro',
    display: 14,
    model: 'MacBook Pro 14 inch M2 Pro (16 Core| 16GB| 512GB)',
    color: ['space gray', 'silver'],
    oldPrice: [55000000],
    actualPrice: [48750000],
    img: [
      './img/mac/macbookpro/macbookpro_m2pro_spacegray.jpeg',
      './img/mac/macbookpro/macbookpro_m2pro_silver.jpeg',
    ],
  },
  {
    id: 13,
    brand: 'apple',
    series: 'macbook pro',
    type: 'M2 Pro',
    display: 14,
    model: 'MacBook Pro 14 inch M2 Pro (19 Core| 16GB| 1TB)',
    color: ['space gray', 'silver'],
    oldPrice: [68000000],
    actualPrice: [60750000],
    img: [
      './img/mac/macbookpro/macbookpro_m2pro_spacegray.jpeg',
      './img/mac/macbookpro/macbookpro_m2pro_silver.jpeg',
    ],
  },

  {
    id: 14,
    brand: 'apple',
    series: 'macbook pro',
    type: 'M2 Pro',
    display: 14,
    model: 'MacBook Pro 14 inch M2 Pro (16 Core| 32GB| 512GB) (CTO)',
    color: ['space gray', 'silver'],
    oldPrice: [59000000],
    actualPrice: [56990000],
    img: [
      './img/mac/macbookpro/macbookpro_m2pro_spacegray.jpeg',
      './img/mac/macbookpro/macbookpro_m2pro_silver.jpeg',
    ],
  },

  {
    id: 15,
    brand: 'apple',
    series: 'macbook pro',
    type: 'M2 Pro',
    display: 16,
    model: 'MacBook Pro 16 inch M2 Pro (19 Core| 16GB| 512GB)',
    color: ['space gray', 'silver'],
    oldPrice: [68000000],
    actualPrice: [60750000],
    img: [
      './img/mac/macbookpro/macbookpro_m2pro_16_spacegray.jpeg',
      './img/mac/macbookpro/macbookpro_m2pro_16_silver.jpeg',
    ],
  },
  {
    id: 16,
    brand: 'apple',
    series: 'macbook pro',
    type: 'M2 Pro',
    display: 16,
    model: 'MacBook Pro 16 inch M2 Pro (19 Core| 16GB| 1TB)',
    color: ['space gray', 'silver'],
    oldPrice: [73000000],
    actualPrice: [65350000],
    img: [
      './img/mac/macbookpro/macbookpro_m2pro_16_spacegray.jpeg',
      './img/mac/macbookpro/macbookpro_m2pro_16_silver.jpeg',
    ],
  },
  {
    id: 17,
    brand: 'apple',
    series: 'macbook pro',
    type: 'M2 Pro',
    display: 16,
    model: 'MacBook Pro 16 inch M2 Pro (19 Core| 32GB| 512GB) - CTO',
    color: ['space gray', 'silver'],
    oldPrice: [72000000],
    actualPrice: [69990000],
    img: [
      './img/mac/macbookpro/macbookpro_m2pro_16_spacegray.jpeg',
      './img/mac/macbookpro/macbookpro_m2pro_16_silver.jpeg',
    ],
  },
  {
    id: 18,
    brand: 'apple',
    series: 'macbook pro',
    type: 'M2 Pro',
    display: 16,
    model: 'MacBook Pro 16 inch M2 Pro (19 Core| 32GB| 1TB) - CTO',
    color: ['space gray', 'silver'],
    oldPrice: [78000000],
    actualPrice: [74990000],
    img: [
      './img/mac/macbookpro/macbookpro_m2pro_16_spacegray.jpeg',
      './img/mac/macbookpro/macbookpro_m2pro_16_silver.jpeg',
    ],
  },

  {
    id: 19,
    brand: 'apple',
    series: 'macbook pro',
    type: 'M2 Max',
    display: 14,
    model: 'MacBook Pro 14 inch M2 Max (30 Core| 32GB| 1TB)',
    color: ['space gray', 'silver'],
    oldPrice: [88000000],
    actualPrice: [73750000],
    img: [
      './img/mac/macbookpro/macbookpro_m2max_spacegray.jpeg',
      './img/mac/macbookpro/macbookpro_m2max_silver.jpeg',
    ],
  },

  {
    id: 20,
    brand: 'apple',
    series: 'macbook pro',
    type: 'M2 Max',
    display: 16,
    model: 'MacBook Pro 16 inch M2 Max (38 Core| 32GB| 1TB)',
    color: ['space gray', 'silver'],
    oldPrice: [94990000],
    actualPrice: [83500000],
    img: [
      './img/mac/macbookpro/macbookpro_m2max_16_spacegray.jpeg',
      './img/mac/macbookpro/macbookpro_m2max_16_silver.jpeg',
    ],
  },
  {
    id: 21,
    brand: 'apple',
    series: 'macbook pro',
    type: 'M2 Max',
    display: 14,
    model: 'MacBook Pro 14 inch M2 Max (30 Core| 64GB| 1TB) - CTO',
    color: ['space gray', 'silver'],
    oldPrice: [92000000],
    actualPrice: [91900000],
    img: [
      './img/mac/macbookpro/macbookpro_m2max_spacegray.jpeg',
      './img/mac/macbookpro/macbookpro_m2max_silver.jpeg',
    ],
  },
];
